steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - eu.gcr.io/cloudrun/persian-website-golang
      - '-f'
      - docker/golang/Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - eu.gcr.io/cloudrun/persian-website-golang