steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - gcr.io/persian-365010/persian-website-golang
      - '-f'
      - docker/V2/Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/persian-365010/persian-website-golang
options:
  logging: CLOUD_LOGGING_ONLY
