CREATE TABLE `Words` (
	`WOID` INT(126) NOT NULL AUTO_INCREMENT UNIQUE,
	`FRAN` VARCHAR(512) NOT NULL,
	`TRAN` VARCHAR(512) NOT NULL,
	`PERS` VARCHAR(512) NOT NULL,
	`LEID` INT(126) NOT NULL,
	`IMAG` BINARY NOT NULL,
	PRIMARY KEY (`WOID`)
);

CREATE TABLE `Lecture` (
	`LEID` INT(126) NOT NULL AUTO_INCREMENT,
	`DATE` DATE NOT NULL,
	PRIMARY KEY (`LEID`)
);

CREATE TABLE `Images` (
	`WOID` INT(126) NOT NULL,
	`NAME` VARCHAR(1028) NOT NULL
);

ALTER TABLE `Words` ADD CONSTRAINT `Words_fk0` FOREIGN KEY (`LEID`) REFERENCES `Lecture`(`LEID`);

ALTER TABLE `Images` ADD CONSTRAINT `Images_fk0` FOREIGN KEY (`WOID`) REFERENCES `Words`(`WOID`);




